### ISSUE TITLE
Тестовое

### ISSUE THREAD

**Issue by Dsitalo** [LazorchikV/task-day-week#1]
Привет, подскажи пожалуйста, это тестовое в Clockwise? Что на него ответили?
И получилось на обучение в Ruby Garage попасть?

**Comment by LazorchikV** [comment]
Это черновик тестового.
В RubyGarage не попал, т. к. не до конца работает программа. Нужно еще PHP
подтянуть.

пн, 15 июн. 2020 г., 22:57 Dmytro <notifications@github.com>:

**Comment by Dsitalo** [comment]
Ясно, мне отказали на задачу по календарю и не ответили почему, решил поискать правильные решения;)
удачи
